import Model.Android;
import Model.Iphone;
import Model.Mobile;
import User.Person;
import User.IPhoneRobot;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }


    public static void main(String[] args) {
        Mobile mobile = new Mobile();
        mobile.setName("Kei");
        mobile.setBrand("Model.Mobile");
        mobile.setColor("Red");
        mobile.setMessage("I use Model.Mobile!");
        System.out.println(mobile.getPhoneInformation());

        System.out.println("|***********************************************|");

        Android android = new Android();
        android.setName("Ke");
        android.setBrand("Samsung");
        android.setColor("Blue");
        android.setMessage("I use Model.Android!");
        System.out.println(android.getPhoneInformation());

        System.out.println("|***********************************************|");

        Iphone iphone = new Iphone();
        iphone.setName("K");
        iphone.setBrand("Model.Iphone");
        iphone.setColor("Blue");
        iphone.setMessage("I use Model.Iphone!");
        System.out.println(iphone.getPhoneInformation());
        System.out.println();

        Person person = new Person("KKei");
        person.makeCall(iphone, "New Teest");

        System.out.println("|***********************************************|");

        IPhoneRobot iphoneRobot = new IPhoneRobot("KKKei");
        iphoneRobot.makeCall(iphone, "New Messagie!");

        System.out.println("|***********************************************|");

       /* IPhoneRobot newIphoneRobot = new IPhoneRobot("KKKei");
        newIphoneRobot.makeCall(android, "New Messagie!");*/


        //System.out.println(new App().getGreeting());
    }
}
